version: "3.8"

# Services
services:
    # Nginx Service
    nginx:
        image: nginx:1.21
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/php
            - ./.docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - php

    # PHP Service
    php:
        build: ./
        working_dir: /var/www/php
        volumes:
            - ./src:/var/www/php
        depends_on:
            - db
        links:
            - db

    db:
        image: mysql:8.0
        cap_add:
            - SYS_NICE
        restart: always
        environment:
            - MYSQL_DATABASE=newsgator
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "3306:3306"
        volumes:
            - db:/var/lib/mysql
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

# Volumes
volumes:
    db:
        driver: local
