version: "3.8"

# Services
services:
    # Composer Service
    composer:
        image: composer:latest
        volumes:
            - ./src:/var/www/php
        working_dir: /var/www/php
        command:
            - composer install
            - composer dump-autoload
